#!/bin/bash

dimension=`xdpyinfo | grep 'dimension' | awk '{print $2}'`

case "$1" in
  start)
    docker run --rm -it \
      --net host \
      --name kali \
      -u kali \
      satotoru/kali:latest bash -c \
      "rm -f /tmp/.X1-lock && vncserver -geometry $dimension && tail -f ~/.vnc/*.log"
    ;;

  exec)
    docker exec -it kali ${@:2}
    ;;
  save)
    docker commit kali satotoru/kali:latest
    ;;

  kill)
    docker kill kali
    ;;

  build)
    docker build . -t satotoru/kali
    ;;

  connect)
    vncviewer 127.0.0.1:5901 -FullScreen
    ;;

  *)
    echo "Usage start|save|build|connect"
    exit 1
    ;;
esac

exit 0
